### ISSUE TITLE
No output generated

### ISSUE THREAD

**Issue by 4rohanjain** [videosegmentation/video_segment#10]
I built the code on a fresh installation of Ubuntu 14.10 using the scripts on this page -->https://docs.google.com/document/d/1idKVuSn-8Muhx4bIk5peXzaaYmDgK8bDgw4mgMn8gUY/edit

I'm running the seg_tree_sample on an input video mp4 file but am not seeing any output mp4.pb file being generated. I can't run the other binaries as I don't have the output to this binary.

Can you help me out with this. What am I doing wrong?

**Comment by dcastro9** [comment]
You have to pass in a flag to get the output.

**Comment by 4rohanjain** [comment]
Can you please inform me what flag to use .
I'm using this command-->
./seg_tree_sample --input_file=INPUT.mp4 --logging --write-to-file

**Comment by dcastro9** [comment]
That should work, what is it printing out?

**Comment by 4rohanjain** [comment]
My apologies, I am actually unable to run the code with the --write-to-file flag:

~/SRC/bin$ ./seg_tree_sample/seg_tree_sample --input_file=../video_segment/video_example/test_video.MOV --logging --write-to-file
ERROR: unknown command line flag 'write-to-file'

However, it runs without it and appears to run through the segmentation... although no output is generated. 

Glog is installed:
$ sudo apt-get install libgoogle-glog-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgoogle-glog-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

Any ideas?

**Comment by dcastro9** [comment]
This is my mistake, the flag is supposed to be write_to_file, i've updated the README, thanks for bringing this up.
